### ISSUE TITLE
High Cost on the Server Side

### ISSUE THREAD

**Issue by SupervisionT** [Alaa-Khattab/node-project#15]
Dear,

I noticed this issue in your code, where you read the data from the text file everytime you have a request. 
(https://github.com/Alaa-Khattab/node-project/blob/master/app/code.js#L2)
This will increase the cost on the server side and will cause high delay and bad user experience as well.
Also you process the results of the text every time inside the function.
(https://github.com/Alaa-Khattab/node-project/blob/master/app/code.js#L10)

In order to solve this issue, I recommend to do this process before calling the server and define it as a global variable then pass it throw the functions.

BR,

**Comment by Alaa-Khattab** [comment]
Thank you for this notice,
It has been corrected :)
