### ISSUE TITLE
.gitignore, I can see the node_modules and npm-debug.log

### ISSUE THREAD

**Issue by besarthoxhaj** [Alaa-Khattab/node-project#7]
I can see the `node_modules` and also `npm-debug.log`.

Usually you don't want this because `node_modules` are installed with `npm install` everytime someone downlaods your code and `npm-debug.log` is the result of some error in you computer while you were trying `npm start`.

Does that make sense?

You can add a `.gitignore` file and add both of them:
```
node_modules
npm-debug.log
```

**Comment by Alaa-Khattab** [comment]
I have hidden them
